# Generated by Django 5.2.6 on 2025-09-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LienData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_party_debtor', models.CharField(max_length=255)),
                ('reverse_party_claimant', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('total_due', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('instrument', models.CharField(blank=True, max_length=50, null=True)),
                ('date_filed', models.CharField(blank=True, max_length=50, null=True)),
                ('book', models.CharField(blank=True, max_length=50, null=True)),
                ('page', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pdf_document_url', models.URLField(blank=True, null=True)),
                ('pdf_file', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_name', models.CharField(max_length=255)),
                ('entity_index', models.IntegerField()),
                ('doc_index', models.IntegerField()),
                ('final_url', models.URLField()),
                ('pdf_viewer', models.URLField()),
                ('screenshot', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
