# Generated by Django 5.2.6 on 2025-09-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_realestatedata_final_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestatedata',
            name='screenshot',
        ),
    ]
