# Generated by Django 5.2.6 on 2025-09-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestatedata',
            name='final_url',
        ),
        migrations.AddField(
            model_name='realestatedata',
            name='realestate_pdf',
            field=models.TextField(blank=True, db_column='RealEstate_PDF', null=True),
        ),
        migrations.AlterField(
            model_name='realestatedata',
            name='pdf_viewer',
            field=models.TextField(blank=True, db_column='PDF_viewer', null=True),
        ),
    ]
